project: 
  type: book
  output-dir: _public
  render:
    - "01_R_Insee/*.qmd"
    - "02_Bonnes_pratiques/*.qmd"
    - "03_Fiches_thematiques/*.qmd"

comments:
  hypothesis: true

book:
  # title: "`utilitR`"
  # author: "Une documentation collaborative"
  # date: last-modified 
  # description: "Documentation utilitR" 
  page-navigation: true
  reader-mode: true
  sharing: [twitter, linkedin]

  page-footer:
    right: |
      <li><a href="https://github.com/InseeFrLab/utilitR.git" target="blank">Code source</a></li>
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/InseeFrLab/utilitR
  repo-actions: [edit,issue]
  repo-branch: master
  favicon: resources/logo-utilitr.png

  navbar:
    search: true
    logo: resources/logo-utilitr.png
    logo-alt: "Logo du projet utilitR"
    background: white
    collapse-below: lg
    left:
      - text: "Introduction"
        href: 01_R_Insee/presentation_utilitr.qmd
      - text: "Mener un projet statistique"
        href: 03_Fiches_thematiques/Fiche_rprojects.qmd
      - text: "Importer des données"
        href: 03_Fiches_thematiques/Fiche_import_fichiers_plats.qmd
      - text: "Choisir son paradigme"
        href: 03_Fiches_thematiques/Fiche_tidyverse.qmd
      - text: "Manipuler des données"
        href: 03_Fiches_thematiques/Fiche_joindre_donnees.qmd
      - text: "Produire des sorties"
        href: 03_Fiches_thematiques/Fiche_graphiques.qmd
      - text: "Bonnes pratiques"
        href: 02_Bonnes_pratiques/01-qualite-code.qmd
  
  sidebar:
    style: "docked"
    search: true
    logo: resources/logo-utilitr.png


  chapters: 
    - index.qmd
    - part: "Introduction"
      chapters:
        - 01_R_Insee/presentation_utilitr.qmd
        - 01_R_Insee/Fiche_utiliser_utilitR.qmd
    - part: "Mener un projet statistique avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_rprojects.qmd
        - 03_Fiches_thematiques/Fiche_git_utilisation.qmd
        - 01_R_Insee/Fiche_installer_packages.qmd
        - 03_Fiches_thematiques/Fiche_comment_choisir_un_package.qmd
        - 03_Fiches_thematiques/Fiche_gerer_dependances.qmd
        - 03_Fiches_thematiques/Fiche_se_documenter.qmd
        - 03_Fiches_thematiques/Fiche_resoudre_un_probleme.qmd
        - 03_Fiches_thematiques/Fiche_targets.qmd
    - part: "Importer des données avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_import_fichiers_plats.qmd
        - 03_Fiches_thematiques/Fiche_import_tables_sas.qmd
        - 03_Fiches_thematiques/Fiche_import_tableurs.qmd
        - 03_Fiches_thematiques/Fiche_import_fichiers_parquet.qmd
        - 03_Fiches_thematiques/Fiche_api.qmd
        - 03_Fiches_thematiques/Fiche_connexion_bdd.qmd
    - part: "Choisir son paradigme d'analyse des données avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_tidyverse.qmd
        - 03_Fiches_thematiques/Fiche_datatable.qmd
        - 03_Fiches_thematiques/Fiche_arrow.qmd
        - 03_Fiches_thematiques/Fiche_duckdb.qmd
    - part: "Manipuler des données avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_joindre_donnees.qmd
        - 03_Fiches_thematiques/Fiche_donnees_textuelles.qmd
        - 03_Fiches_thematiques/Fiche_survey.qmd
        - 03_Fiches_thematiques/Fiche_donnees_spatiales.qmd
        - 03_Fiches_thematiques/Fiche_donnees_temporelles.qmd
        - 03_Fiches_thematiques/Fiche_analyse_de_donnees.qmd
    - part: "Produire des sorties avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_graphiques.qmd
        - 03_Fiches_thematiques/Fiche_rmarkdown.qmd
        - 03_Fiches_thematiques/Fiche_rmarkdown_param_report.qmd
    - part: "Bonnes pratiques"
      chapters:
        - 02_Bonnes_pratiques/01-qualite-code.qmd
        - 02_Bonnes_pratiques/02-structure-code.qmd
    - part: "Éléments de configuration"
      chapters:
        - 01_R_Insee/Fiche_utiliser_Rstudio_AUSv3.qmd
        - 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.qmd
        - 03_Fiches_thematiques/Fiche_configurer_git.qmd
        - 01_R_Insee/Fiche-personnaliser-R.qmd
        - 01_R_Insee/Fiche_utiliser_ressources.qmd

# not sure what the following line does; those files are present
# bibliography: [references.bib, book.bib]

format:
  html:
    theme:
      light: [cosmo, css/style.css, css/style-utilitr.css, css/style.scss]
      dark:  [darkly, css/style.css, css/style-utilitr.css, css/style.scss]
    code-link: true
    code-copy: true
    code-overflow: wrap
    toc: true

