project: 
  type: book
  output-dir: _public



book:
  title: "Documentation collaborative `utilitR`"
  # author: "Une documentation collaborative"
  # date: last-modified 
  # description: "Documentation utilitR" 
  page-navigation: true
  reader-mode: true
  sharing: [twitter, linkedin]
  
  #sidebar:
    #logo: "resources/logo-utilitR.png"

  page-footer:
    right: |
      <li><a href="https://github.com/InseeFrLab/utilitR.git" target="blank">Code source</a></li>
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://www.book.utilitr.org/
  repo-url: https://github.com/InseeFrLab/utilitR
  repo-actions: [edit,issue]
  cover-image: resources/logo-utilitr.png
  favicon: resources/logo-utilitr.png

  # navbar:
  #   search: true
  #   logo: resources/logo-utilitr.png
  #   background: white
    
  sidebar:
    search: true
    logo: resources/logo-utilitr.png
  

  chapters: 
    - index.qmd
    - 01_R_Insee/Fiche_utiliser_utilitR.qmd
    - part: "Comment utiliser R"
      chapters:
        - 01_R_Insee/Fiche_utiliser_Rstudio_AUSv3.qmd
        - 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.qmd
        - 03_Fiches_thematiques/Fiche_configurer_git.qmd
        - 01_R_Insee/Fiche-personnaliser-R.qmd
        - 01_R_Insee/Fiche_utiliser_ressources.qmd
    - part: "Mener un projet statistique avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_rprojects.qmd
        - 03_Fiches_thematiques/Fiche_git_utilisation.qmd
        - 01_R_Insee/Fiche_installer_packages.qmd
        - 03_Fiches_thematiques/Fiche_comment_choisir_un_package.qmd
        - 03_Fiches_thematiques/Fiche_gerer_dependances.qmd
        - 03_Fiches_thematiques/Fiche_se_documenter.qmd
        - 03_Fiches_thematiques/Fiche_resoudre_un_probleme.qmd
        - 03_Fiches_thematiques/Fiche_targets.qmd
    - part: "Importer des donn√©es avec R"
      chapters:
        - 03_Fiches_thematiques/Fiche_import_fichiers_plats.qmd
        - 03_Fiches_thematiques/Fiche_import_tables_sas.qmd
        - 03_Fiches_thematiques/Fiche_import_tableurs.qmd
        - 03_Fiches_thematiques/Fiche_api.qmd
        - 03_Fiches_thematiques/Fiche_connexion_bdd.qmd
        - 03_Fiches_thematiques/Intro_partie_manipuler_donnees.qmd
        - 03_Fiches_thematiques/Fiche_tidyverse.qmd
        - 03_Fiches_thematiques/Fiche_datatable.qmd
        - 03_Fiches_thematiques/Fiche_joindre_donnees.qmd
        - 03_Fiches_thematiques/Fiche_donnees_textuelles.qmd
        - 03_Fiches_thematiques/Fiche_survey.qmd
        - 03_Fiches_thematiques/Fiche_donnees_spatiales.qmd
        - 03_Fiches_thematiques/Fiche_analyse_de_donnees.qmd
    - part: "Produire des sorties avec R"
      chapters:
      - 03_Fiches_thematiques/Fiche_graphiques.qmd
      - 03_Fiches_thematiques/Fiche_rmarkdown.qmd
      - 03_Fiches_thematiques/Fiche_rmarkdown_param_report.qmd

# not sure what the following line does; those files are present
# bibliography: [references.bib, book.bib]

format:
  html:
    theme:
      - cosmo
      - css/style.css
      - css/style-utilitr.css
      - css/box.scss
    code-link: true
    code-copy: true
    code-overflow: wrap
    toc: true
#   utilitr::html_paged:
#     new_session: yes
#     self_contained: false
#     front_cover: "resources/logo-utilitR.svg"
#   utilitr::bs4_utilitr:
#     repo: https://github.com/InseeFrLab/utilitR
#     css:
#     - css/logo-path.css    
