on:
  push:
    branches-ignore:
      - master
      - main

name: preview pagedown

jobs:
  build:
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      # - name: mogrify images
      #   run: |
      #     find ./pics -name '*.png' -exec mogrify -resize 512x512 {} +   convert *.png -resize 512x512 -set filename:f '%t' ../'%[filename:f].png'
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('remotes','rmarkdown','bookdown'))"
          Rscript -e "remotes::install_github('rstudio/pagedown')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render Book
        run: |
          mkdir _pagedown_output
          Rscript -e "bookdown::render_book('index.Rmd', output_format = 'pagedown::html_paged', output_file = '_pagedown_output/index.html')"
          Rscript -e "pagedown::chrome_print('_pagedown_output/index.html', '_pagedown_output/DocumentationR.pdf', extra_args = c('--disable-gpu', '--no-sandbox'), timeout = 300, options = list(transferMode = 'ReturnAsStream'), verbose = 1)"
      - name: Compress PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=_pagedown_output/DocumentationR.pdf _pagedown_output/DocumentationR.pdf
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationR_pagedown
          path: _pagedown_output/
          # name: DocumentationR_pagedown
          # path: DocumentationR.pdf

#--site="$NETLIFY_SITE_ID" --auth="$NETLIFY_AUTH_TOKEN"